services:
  web:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    command: sh -c "/usr/local/bin/wait-for-db && gunicorn wsgi:app --config gunicorn.conf.py --log-level debug"
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always # Ensure the service restarts if it crashes
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    # No port mapping for production usually, services connect internally
    # - "5432:5432"
    restart: always

  redis:
    image: redis:6.2-alpine
    restart: always

  worker:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - PYTHONPATH=/app
    command: sh -c "/usr/local/bin/wait-for-db && celery -A celery_app:celery_app worker --loglevel=info"
    env_file:
      - .env
    restart: always # Ensure the service restarts if it crashes
    depends_on:
      - redis
      - db

  test:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

volumes:
  postgres_data:
