from app.models.user import User, UserRole
from app.extensions import bcrypt

def test_user_creation(init_database):
    """
    Test that a user can be created and saved to the database.
    """
    user = User(email='create@example.com', role=UserRole.MOVER)
    user.set_password('securepassword')
    init_database.session.add(user)
    init_database.session.commit()

    assert user.id is not None
    assert user.email == 'create@example.com'
    assert user.role == UserRole.MOVER
    assert user.password_hash is not None

def test_user_set_and_check_password(sample_user):
    """
    Test setting and checking user passwords.
    """
    assert sample_user.check_password('password123')
    assert not sample_user.check_password('wrongpassword')

def test_user_password_hashing(sample_user):
    """
    Test that the password hash is correctly generated by bcrypt.
    """
    # Verify that the password hash is not plain text
    assert sample_user.password_hash != 'password123'
    # Verify that the hash can be verified by bcrypt
    assert bcrypt.check_password_hash(sample_user.password_hash, 'password123')

def test_user_role_enum(init_database):
    """
    Test that user roles are correctly handled by the enum.
    """
    customer_user = User(email='customer@example.com', role=UserRole.CUSTOMER)
    customer_user.set_password('pass1')
    init_database.session.add(customer_user)
    init_database.session.commit()

    admin_user = User(email='admin@example.com', role=UserRole.ADMIN)
    admin_user.set_password('pass2')
    init_database.session.add(admin_user)
    init_database.session.commit()

    assert customer_user.role == UserRole.CUSTOMER
    assert admin_user.role == UserRole.ADMIN

def test_user_to_dict_method(sample_user):
    """
    Test the to_dict method excludes password_hash.
    """
    user_dict = sample_user.to_dict()
    assert 'password_hash' not in user_dict
    assert user_dict['email'] == 'test@example.com'
    assert user_dict['role'] == 'customer' # Enum converted to string in dict

def test_user_save_and_delete(init_database):
    """
    Test the save and delete methods from BaseModel.
    """
    user = User(email='temp@example.com', role=UserRole.CUSTOMER)
    user.set_password('temp_pass')
    user.save() # Uses BaseModel save method
    init_database.session.commit()
    assert user.id is not None

    user_from_db = init_database.session.get(User, user.id)
    assert user_from_db is not None
    assert user_from_db.email == 'temp@example.com'

    user.delete() # Uses BaseModel delete method
    init_database.session.commit()
    user_after_delete = init_database.session.get(User, user.id)
    assert user_after_delete is None
