"""Add index to user role

Revision ID: ad8f6e5154f2
Revises: 365435b2a4df
Create Date: 2026-02-11 11:00:33.871524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8f6e5154f2'
down_revision = '365435b2a4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    # ### end Alembic commands ###
