"""Add first_name and last_name to users table

Revision ID: c888ea7b4c4a
Revises: fbd8b65c4f9d
Create Date: 2026-02-12 11:51:25.233123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c888ea7b4c4a'
down_revision = 'fbd8b65c4f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_index(op.f('ix_bookings_dropoff_address_id'), 'bookings', ['dropoff_address_id'], unique=False)
    op.create_index(op.f('ix_bookings_mover_id'), 'bookings', ['mover_id'], unique=False)
    op.create_index(op.f('ix_bookings_pickup_address_id'), 'bookings', ['pickup_address_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_index(op.f('ix_inventories_booking_id'), 'inventories', ['booking_id'], unique=False)
    op.create_index(op.f('ix_messages_booking_id'), 'messages', ['booking_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_movers_user_id'), 'movers', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_quotes_dropoff_address_id'), 'quotes', ['dropoff_address_id'], unique=False)
    op.create_index(op.f('ix_quotes_mover_id'), 'quotes', ['mover_id'], unique=False)
    op.create_index(op.f('ix_quotes_pickup_address_id'), 'quotes', ['pickup_address_id'], unique=False)
    op.create_index(op.f('ix_quotes_user_id'), 'quotes', ['user_id'], unique=False)
    op.create_index(op.f('ix_reviews_booking_id'), 'reviews', ['booking_id'], unique=False)
    op.create_index(op.f('ix_reviews_mover_id'), 'reviews', ['mover_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_mover_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_booking_id'), table_name='reviews')
    op.drop_index(op.f('ix_quotes_user_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_pickup_address_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_mover_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_dropoff_address_id'), table_name='quotes')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_movers_user_id'), table_name='movers')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_booking_id'), table_name='messages')
    op.drop_index(op.f('ix_inventories_booking_id'), table_name='inventories')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_pickup_address_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_mover_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_dropoff_address_id'), table_name='bookings')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    # ### end Alembic commands ###
