"""Add recommended indexes

Revision ID: fbd8b65c4f9d
Revises: ad8f6e5154f2
Create Date: 2026-02-11 11:03:29.766145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd8b65c4f9d'
down_revision = 'ad8f6e5154f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_addresses_zip_code'), 'addresses', ['zip_code'], unique=False)
    op.create_index(op.f('ix_bookings_booking_time'), 'bookings', ['booking_time'], unique=False)
    op.create_index(op.f('ix_bookings_checkout_request_id'), 'bookings', ['checkout_request_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_movers_approved'), 'movers', ['approved'], unique=False)
    op.create_index(op.f('ix_movers_company_name'), 'movers', ['company_name'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_quotes_status'), 'quotes', ['status'], unique=False)
    op.create_index(op.f('ix_reviews_rating'), 'reviews', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_rating'), table_name='reviews')
    op.drop_index(op.f('ix_quotes_status'), table_name='quotes')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_movers_company_name'), table_name='movers')
    op.drop_index(op.f('ix_movers_approved'), table_name='movers')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_checkout_request_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_time'), table_name='bookings')
    op.drop_index(op.f('ix_addresses_zip_code'), table_name='addresses')
    # ### end Alembic commands ###
